[package]
name = "bakery-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.28"
sea-orm = { version = "^0.12.0", features = [ "sqlx-postgres", "runtime-async-std-native-tls", "macros", "mock" ] }
